[package]
name = "dot-protector"
version = "0.1.0"
authors = ["Zach Probst <Zach_Probst@intuit.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
